### ISSUE TITLE
Le ruote sono imbarazzanti

### ISSUE THREAD

**Issue by sebgiles** [Robotics-UNIVPM/mapper#10]

**Comment by marcofrn23** [comment]
difficilmente le vostre sono peggio delle mie, quando il motore riceve la massima potenza prendono anche una campanatura convergente

**Comment by sebgiles** [comment]
Comunque avevamo previsto anche prima di comprarli che sarebbero state da sostituire.
Una delle mie ha un piccola crepa per cui non stringe bene sull'asse, balla e si stacca dopo un minuto di guida...

**Comment by sebgiles** [comment]
Nuovo chassis in Lego
