### ISSUE TITLE
Campi magnetici

### ISSUE THREAD

**Issue by sebgiles** [Robotics-UNIVPM/mapper#12]
Se saranno impiegati magnetometri è importante che vengano posizionati in modo da non ricevere interferenze. Sto usando una bussola analogica per debuggare 😆

**Comment by xn3cr0nx** [comment]
I campi magnetici creati dagli avvolgimenti dei motori in continua credi possano interferire con il campo del sensore? Farebbe un po' schifo

**Comment by sebgiles** [comment]
Nei motori DC ci sono magneti permanenti...

**Comment by xn3cr0nx** [comment]
Avrò studiato altri modelli di motori allora

**Comment by sebgiles** [comment]
probabilmente erano motori a induzione. 
adesso chiudo visto che il magnetometro è stato messo da parte
