### ISSUE TITLE
un'immagine vale più di mille parole

### ISSUE THREAD

**Issue by sebgiles** [Robotics-UNIVPM/mapper#14]
#Real Time Plots
dovrebbe essere semplice estendere lo script del serial read per fare disegni in tempo reale dei dati man mano che vengono scritti su file
Python è lo standard attuale per l'ambito scientifico ed è ben predisposto.
Se qualcuno avesse tempo e voglia potrebbe sfruttare matplotlib

**Comment by lorisrossi** [comment]
Mi sembra che Patrick abbia già fatto una cosa simile in Python
Sarebbe molto carina una cosa del genere <img src="http://www.cohort.com/animatedxaxis.gif">
o comunque un qualcosa sulla falsa riga di questo
Sono d'accordo sul fatto che se qualcuno ha voglia potrebbe provare a farlo

**Comment by xn3cr0nx** [comment]
Si io ho lo script in cui viene creato proprio un oggetto plot analogico, volendo si potrebbe studiare il funzionamento di quello. Le librerie coinvolte fondamentale sono parse e serial per la gestione del segnale attraverso la porta e matplotlib per fare il plot. Se ne può discutere la prossima volta

**Comment by sebgiles** [comment]
per ora abbiamo ben due soluzioni, per questo problema: Matlab e Python
