### ISSUE TITLE
meno modifiche su master

### ISSUE THREAD

**Issue by sebgiles** [Robotics-UNIVPM/mapper#19]
Con riferimento a: https://github.com/Robotics-UNIVPM/mapper/network

Se facessimo meno modifiche sul master ma usassimo più "rami dedicati" sarebbe più facile leggere le modifiche in modo logico.

dite la vostra poi chiudiamo l'issue

**Comment by Clacly96** [comment]
Io ho aperto stamattina un branch per l'esp (credo di averlo fatto nel modo corretto); è questo che intendevi?

**Comment by sebgiles** [comment]
Sì direi di seguire quel pattern però evitando di cancellare il branch se si prevedono altre modifiche entro breve tempo sullo stesso argomento. 
Una branch per ogni gruppo che continui a esistere finché il relativo lavoro non sia completato con regolari merge verso master per i log e merge da master solo se necessari.
Ovviamente imporre una rigidezza del genere è quasi completamente inutile per i nostri scopi, è per esplorare come usare git.
