### ISSUE TITLE
Se usiamo un raspberry per acquisire i dati con seriale?

### ISSUE THREAD

**Issue by Clacly96** [Robotics-UNIVPM/mapper#23]

**Comment by sebgiles** [comment]
Quali sarebbero i vantaggi?

**Comment by Clacly96** [comment]
Di non avere il robot collegato in wifi, durante l'analisi vengono creati i file su Raspberry e alla fine li prendiamo da raspberry e li analizziamo. (è un vantaggio se non ci interessa l'analisi in tempo reale)

**Comment by robbroc** [comment]
Si era già discusso di ciò mi pare, e la proposta era stata bocciata. Non è strettamente necessario raspberry, anche perché ancora non conosciamo i limiti del microcontrollore del modulo WiFi che potrebbero permetterci di gestire diversamente la cosa, direi che lunedì, dopo le dovute verifiche possiamo considerare le alternative, fino ad allora è inutile discutere senza fatti certi.

**Comment by sebgiles** [comment]
Butto giù le idee che mi vengono
- A progetto compiuto avere robot indipendenti sarebbe più elegante
- Protocolli di rete non necessari (per un singolo robot)
- Latenza minore tra algoritmi di mappatura e mondo fisico
- Espansibilità (es videocamera)
- Pi può flashare il micro
- Sviluppare su Pi richiede che questo sia comunque connesso ad una rete (SSH)
- Graficare dati in tempo reale richiede comunque protocolli di rete
- Pi ha potenza di calcolo inferiore
- Compilare per micro su Pi è lento
- Sistema operativo da mantenere 
- Consumo energetico potrebbe richiedere alimentazione separata
- Ingombro
- Costo

**Comment by orazioedoardo** [comment]
Ho un Raspberry Pi 3 se vi serve per qualche prova, in oltre mi pare che all'occorrenza si possa ottenere una shell via seriale con un cavo come [questo](https://www.sparkfun.com/products/12977).

**Comment by sebgiles** [comment]
Pi3 integra il wifi, mentre di UART ce n'è una sola, se non sbaglio, e andrebbe usata per il micro!
Comunque auguri Orazio!

**Comment by orazioedoardo** [comment]
Dall'esterno non ho capito esattamente come si configura il progetto però volendo il RPi può farvi da access point (visto che mi sembra che ne usiate uno), interagendo via SSH ma lasciando i pin GPIO liberi. Chiaramente vedete voi la fattibilità.

**Comment by sebgiles** [comment]
Ancora non c'è un progetto completo, più o meno l'idea è questa:

motori e sensori <---> Arduino <---> Esp8266 <---> Router <---> Computer

L'obbiettivo è che il computer esegua un algoritmo per costruire una mappa dell'ambiente in cui i robot si muovono. La comunicazione è bidirezionale, nel senso che il computer può chiedere ai robot di esplorare delle zone interessanti al fine di completare la mappa.
Per ora dobbiamo ancora valutare la memoria e la potenza di calcolo necessaria per elaborare i dati dei sensori e guidare il robot in modo controllato, lo spazio che avanza sarà utile per la comunicazione.

**Comment by orazioedoardo** [comment]
Quindi è ancora presto per dirlo, detto ciò mi viene in mente che un RPi avrebbe senso se potesse sostituire "Router <---> Computer", magari lo lasciate come possibile alternativa finale dopo aver organizzato il tutto con la configurazione attuale. Penso che sarebbe più elegante di un router e un computer di mezzo (anche se alla fine un computer per visualizzare la mappatura ci vuole).

**Comment by sebgiles** [comment]
se emerge qualche problema con lo stato attuale lo riprendiamo in considerazione
