### ISSUE TITLE
Modello cinematico-dinamico

### ISSUE THREAD

**Issue by sebgiles** [Robotics-UNIVPM/mapper#29]
Comincio con due domande e mi risponderò anche da solo, aggiungete se potete
1 - Che tipo di modello cinematico?

2 - Facciamo anche un modello dinamico? Come?

**Comment by lorisrossi** [comment]
Patrick sta leggendo qualcosa a riguardo, il nostro robot dovrebbe essere del tipo "hilare-type", ci sono già alcuni modelli su internet
Comunque direi di discuterne insieme in laboratorio

**Comment by sebgiles** [comment]
ok, io me lo studio un po', quello che trovo lo metto qui prima di Lunedì, così possiamo guardare questo thread mentre discutiamo, voi fate uguale se volete

**Comment by sebgiles** [comment]
L'angolo di imbardata è univocamente determinato dalla differenza delle distanze percorse dalle ruote, lo dico intuitivamente, ma andrebbe dimostrato matematicamente (e potrebbe anche non essere vero).
<img width="698" alt="cin" src="https://cloud.githubusercontent.com/assets/3638098/20642434/e85e2728-b40e-11e6-9c6c-a9375359a69a.png">

[traiettoria.pdf](https://github.com/Robotics-UNIVPM/mapper/files/614368/cinematica.rover.1.pdf)

Gli integrali non sono algebricamente risolvibili. Lunedì vorrei provare a implementarlo numericamente con Matlab per vedere se funziona.

**Comment by sebgiles** [comment]
@lorisrossi il fatto che gli integrali non siano risolvibili mi sembra coerente con il fatto che è necessario tenere conto di tutto il percorso passato
