### ISSUE TITLE
protocollo errori

### ISSUE THREAD

**Issue by xn3cr0nx** [Robotics-UNIVPM/mapper#46]
Si studia un modo per avere i dati sempre puliti. In questa soluzione risulterà una matrice di n righe, valore da noi definito a piacere, con ogni riga composta da un valore di check sulla prima colonna, che a priori è dato come un valore a scelta, nelle 4 colonne centrali i valori acquisiti da encoder dx e sx, sonar e tempo, infine sull'ultima colonna un'altro valore di check di controllo diverso dal precedente. Il mio codice MATLAB non sono sicuro sia corretto a livello sintattico senza provarlo, ancor meno sono sicuro di aver tenuto conto di tutti i problemi. L' ultima parte con il while la cambierei volentieri perchè si butta via l'intera riga dopo ma prima non mi è venuta in mente altra soluzione. Allego codice e flowchart per la logica 

[Protocollo_Errori.pdf](https://github.com/Robotics-UNIVPM/mapper/files/637548/Protocollo_Errori.pdf)
[protocollo.txt](https://github.com/Robotics-UNIVPM/mapper/files/637549/protocollo.txt)

**Comment by lorisrossi** [comment]
Ho seguito una logica simile, cambia il modo di salvare la matrice e il momento in cui si fa il controllo sul check iniziale.

- Guardo se il check iniziale è giusto; se è sbagliato, cerco il check successivo, e quando lo trovo continuo.
- Leggo i dati che mi servono.
- Check finale; se è sbagliato, non salvo i dati letti, se invece è giusto li salvo, aggiungendo una riga alla matrice.

Spiego la logica sul check iniziale, mi rendo conto che è un po' incasinata:
Il check iniziale è a 16 bit (2 byte)
Metto tutto dentro a un while, in cui controllo che il secondo byte trovato corrisponda a quello del check.
Per come è strutturato il programma, la riga "if x2 == CHECK_IN_1" ha senso solo dopo il primo ciclo di while, infatti se x2 non è il 2 byte del check, potrebbe esserne il primo, quindi devo verificarlo prima di leggere un nuovo dato.
Se questo check non passa, leggo un byte e lo confronto col primo byte del check (CHECK_IN_1). Se è quello, controllo il successivo, sperando che sia il secondo byte del check (CHECK_IN_2)

```
x2 = 0;
data = [];
for i = 1:number
   check1 = read(t, 1, 'int16');
   if check1 ~= CHECK_IN
       while x2 ~= CHECK_IN_2
           if x2 == CHECK_IN_1
               x2 = read(t, 1, 'int8');
           else
               x1 = read(t, 1, 'int8');
               if x1 == CHECK_IN_1
                   x2 = read(t, 1, 'int8');
               end
           end
       end           
   end
   
   encL = read(t, 1, 'int32');
   encR = read(t, 1, 'int32');
   time = read(t, 1, 'int32');
   sonar = read(t, 1, 'int32');
   
   check2 = read(t, 1, 'int8');
   if check2 ~= CHECK_OUT
       continue
   end
   
   data = [data; encL encR time sonar];
   
end
```

Ovviamente non ho potuto testarlo, è sicuramente migliorabile e probabilmente ci sono modi più efficienti per gestire il check, ditemi cosa ne pensate
